### ISSUE TITLE
change_volume error

### ISSUE THREAD

**Issue by WegoW** [RoonLabs/node-roon-api-transport#2]
transport.change_volume(zone, "absolute", 20) gives the following error:

```
> REQUEST 3 com.roonlabs.transport:1/change_volume {"how":"absolute","value":20}
<- COMPLETE 3 InvalidRequest {"message":"JSON: missing required string field: output_id"}
```

But passing an output instead of a zone is working.
transport.change_volume(zone.outputs[0], "absolute", 20);

As you mentioned in the forum, zone should work too.

**Comment by dannyfiresnake** [comment]
looking deeper into this, I said the wrong thing.. you are doing the right thing by passing the output.

I've added more documentation and setup a github pages to host those docs.

https://roonlabs.github.io/node-roon-api-transport/

If you have more docs or info, I'll gladly take a pull request :-)
