### ISSUE TITLE
typo in function zoid() ?

### ISSUE THREAD

**Issue by WegoW** [RoonLabs/node-roon-api-transport#3]
Shouldn't this be "zo" instead of "o" in the 2nd line?

function zoid(zo) {
    if (typeof(o) == 'string') return o;
    if (zo.output_id) return zo.output_id;
    return zo.zone_id;
}

**Comment by dannyfiresnake** [comment]
fixed. sorry! 78c5042

it only impacted callers that were calling by id, which is very rare
