### ISSUE TITLE
lib.js zone_by_zone_id function does not return the zone

### ISSUE THREAD

**Issue by st0g1e** [RoonLabs/node-roon-api-transport#5]
Hi,

I found that the zone_by_zone_id does not return the zone, I have found the fix (that works for me, at least). 

RoonApiTransport.prototype.zone_by_zone_id = function(zone_id) {
    if (!this._zones) return null;
//    for (var x in this._zones) if (x == zone_id) return this._zones[x];
    for (var x in this._zones) if (this._zones[x].zone_id == zone_id) return this._zones[x];
    return null;
}

Please let me know if the change is correct.

Thank you,
Bastian

**Comment by dannyfiresnake** [comment]
Does it fix your issue? I ask because it should not. They key in that _zones map is the zone id.

**Comment by st0g1e** [comment]
Hi Danny,

Yes, it works.
I apologize to update and close this.
The problem was I was using array instead of hash in my code for zone_list. 

just to confirm, the key is always the same as zone_id
