### ISSUE TITLE
Standby interface is not documented/exposed

### ISSUE THREAD

**Issue by JanKoudijs** [RoonLabs/node-roon-api-transport#7]
There is no API documented/exposed that provides switching a single device into standby (e.g. by providing an output_id).

**Comment by dannyfiresnake** [comment]
done 9f1eeda

**Comment by dannyfiresnake** [comment]
note that multiple things on an output can be put into standby... one could theoretically have a device with an amp and a dac with different and independent types of standby support. That's the point of the `control_key`
