### ISSUE TITLE
A few issues in new standby/convenience_switch interfaces

### ISSUE THREAD

**Issue by JanKoudijs** [RoonLabs/node-roon-api-transport#8]
There are a few parameter mismatches in the newly added standby/convenience_switch interfaces.
The toggle standby interface is missing the 'toggle' in its name.
Patch attached.
[lib.js.patch.txt](https://github.com/RoonLabs/node-roon-api-transport/files/917557/lib.js.patch.txt)

**Comment by dannyfiresnake** [comment]
incorporated these in aead0a8

github supports the "pull request", which means you can fork my repo, make changes in your forked copy, and then push your changes over to me, and with 1 click I can incorporate them. Much easier than a patch :-)

**Comment by JanKoudijs** [comment]
Next time I will create a pull request.
Thanks for applying.
