### ISSUE TITLE
change_volume()'s callback executes before state change.

### ISSUE THREAD

**Issue by haysclark** [RoonLabs/node-roon-api-transport#9]
Based on the [docs for change_volume](https://roonlabs.github.io/node-roon-api/RoonApiTransport.html#change_volume) I was expecting the callback (cb) to be called after the state change has occurred.

    core.services.RoonApiTransport.change_volume(outputId, how, value, (err) => {
        // callback is called yet volume has yet to be changed if you query the state.
        console.log(core.services.RoonApiTransport.zone_by_zone_id(zoneId));
    });

**Comment by blucz** [comment]
Fixed pending the next release of Roon.
